---
title: "Data Intelligence"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
    social: ["menu"]
    source_code: embed
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(tidyverse)
library(fontawesome)
library(plotly)
library(palmerpenguins)
data("penguins")

```

Plots {data-navmenu="Pages"}
======================================================================

sidebar{.sidebar}
----------------------------------------------------------------------

### Stats About The Data

The number of penguins is `r nrow(penguins)`


Row
-----------------------------------------------------------------------

### Number of Penguins

```{r}
valueBox(nrow(penguins), icon = "fa-linux")

```

### Average Body Mass

```{r}

Average_Mass =  round(mean(penguins$body_mass_g, na.rm=TRUE), 1)

gauge(Average_Mass,
      min(0),
      max(penguins$body_mass_g, na.rm=TRUE),
      gaugeSectors(success = c(4000, 6300),
                   warning = c(2000, 3999),
                   danger  =  c(0, 1999))
      )

```


Column {.tabset}
-----------------------------------------------------------------------

### Scatter Plot

```{r}

 p1 = penguins %>% ggplot( aes(x = bill_length_mm, y = bill_depth_mm, color = species ) )+
      geom_point()

ggplotly(p1)
     

```

### Boxplot

```{r}
    penguins %>% ggplot(aes(x = body_mass_g, y =  sex, fill = sex))+
          geom_boxplot()



```

### Histogram

```{r}

 p3 <- penguins %>% ggplot(aes(x = flipper_length_mm, fill = species))+
                  geom_histogram()+facet_wrap(~species)
      
ggplotly(p3)


```


Data {data-navmenu="Pages"}
================================================================================
```{r}
penguins %>% datatable(extensions = "Buttons",
                       options = list(dom = "Blfrtip", 
                                      buttons = c("csv", "copy",
                                              "pdf", "excel", "print")
                                      ))
```

